package promovolve.taxonomy

import scala.annotation.tailrec
import scala.io.Source
import scala.util.Using

/** What level of the hierarchy a [[Place]] sits at. */
enum PlaceKind:
  case Country, Subdivision, City

/**
 * One node of the geographic vocabulary.
 *
 * `parent` is the code of the enclosing place, never derived by parsing
 * `code`. City codes are opaque GeoNames ids precisely so nobody is
 * tempted to infer structure from the string.
 */
final case class Place(
    code: String,
    name: String, // English, canonical — feeds prompts and matching
    kind: PlaceKind,
    parent: Option[String],
    population: Long = 0L
)

/**
 * The closed geographic vocabulary: countries (ISO 3166-1 alpha-2),
 * first-level subdivisions (ISO 3166-2), and cities (GeoNames ids,
 * prefixed `GN`).
 *
 * Closed is the point. Every geographic value that enters the system —
 * an LLM's answer about what a page is about, a publisher's audience
 * declaration, an advertiser's targeting set — is checked against this
 * table and dropped if absent, so downstream matching is plain set
 * intersection over a vocabulary both sides share. See
 * `docs/design/GEOGRAPHIC_CONTEXT.md`.
 *
 * Tables are generated by `scripts/build-places.sh`; codes come from ISO
 * and cities from GeoNames. The two disagree about subdivision numbering
 * (GeoNames JP.13 is Hyogo, ISO JP-13 is Tokyo), which is why the build
 * links cities to ISO subdivisions by name and leaves `parent` at the
 * country when it cannot match confidently — a coarser answer, never a
 * wrong one.
 */
object Places {

  private val CountriesPath = "/places/countries"
  private val SubdivisionsPath = "/places/subdivisions"
  private val CitiesPath = "/places/cities"
  // Search-only names: every OTHER localised name GeoNames knows for a
  // place (アメリカ beside the catalogue's 米国, ロス beside ロサンゼルス).
  // Many rows per code, never shown — display stays the one curated name.
  private val AliasesPath = "/places/aliases"

  private lazy val byCode: Map[String, Place] = {
    val countries = loadTsv(s"$CountriesPath.tsv", 2) { cols =>
      Place(cols(0), cols(1), PlaceKind.Country, None)
    }
    val subdivisions = loadTsv(s"$SubdivisionsPath.tsv", 3) { cols =>
      Place(cols(0), cols(2), PlaceKind.Subdivision, Some(cols(1)))
    }
    val cities = loadTsv(s"$CitiesPath.tsv", 5) { cols =>
      // admin1 may be blank when the build could not map GeoNames'
      // admin1 onto an ISO subdivision; the city then hangs off its
      // country directly.
      val parent = if (cols(3).nonEmpty) cols(3) else cols(2)
      Place(cols(0), cols(1), PlaceKind.City, Some(parent), cols(4).toLongOption.getOrElse(0L))
    }
    (countries ++ subdivisions ++ cities).map(p => p.code -> p).toMap
  }

  /** Localized display names per compiled-in language, keyed by place code. */
  private lazy val localized: Map[String, Map[String, String]] = {
    val perFile = List(CountriesPath, SubdivisionsPath, CitiesPath).map(LocalizedNames.loadAll)
    LocalizedNames.langs.map { lang =>
      lang -> perFile.foldLeft(Map.empty[String, String])((acc, m) => acc ++ m.getOrElse(lang, Map.empty))
    }.toMap
  }

  /** Search-only aliases per compiled-in language, as (code, name) rows. */
  private lazy val aliases: Vector[(String, String)] =
    LocalizedNames.langs.toVector.flatMap { lang =>
      Option(getClass.getResourceAsStream(s"${AliasesPath}_$lang.tsv")) match {
        case None     => Vector.empty // optional table: search is merely narrower without it
        case Some(is) =>
          Using(Source.fromInputStream(is, "UTF-8")) { source =>
            source
              .getLines()
              .drop(1)
              .filter(_.nonEmpty)
              .map(_.split("\t", -1))
              .collect { case cols if cols.length >= 2 && cols(0).nonEmpty && cols(1).nonEmpty => cols(0) -> cols(1) }
              .toVector
          }.getOrElse(Vector.empty)
      }
    }

  /** Search index: normalized name → codes, built once from every language plus aliases. */
  private lazy val searchIndex: Vector[(String, Place)] = {
    val locales = localized.values.flatten.toVector ++ aliases
    val fromLocal = locales.flatMap { case (code, name) => byCode.get(code).map(p => normalize(name) -> p) }
    val fromEn = byCode.valuesIterator.map(p => normalize(p.name) -> p).toVector
    (fromEn ++ fromLocal).distinct
  }

  /**
   * Cities by normalized name (English and every localized name), for
   * resolving a classifier-emitted "City, CODE" pair. Built from the
   * search index so the two agree on what a name is.
   */
  private lazy val citiesByName: Map[String, Vector[Place]] =
    searchIndex.iterator
      .collect { case (name, p) if p.kind == PlaceKind.City => name -> p }
      .toVector
      .groupMap(_._1)(_._2)
      .view
      .mapValues(_.distinctBy(_.code).sortBy(p => (-p.population, p.code)))
      .toMap

  def get(code: String): Option[Place] = byCode.get(code)

  def contains(code: String): Boolean = byCode.contains(code)

  /**
   * Resolve a city NAME to a city code, scoped to the place it sits in.
   *
   * This is the door the design doc left "cheap to open": the classifier
   * can name a town, but the disambiguation that made tier 1 stop at
   * subdivision is done HERE, by scope, not trusted to the model —
   * "Springfield" means nothing, "Springfield, US-IL" means one thing.
   *
   *   - `within` must be a known country or subdivision; the city must
   *     have it as an ancestor.
   *   - Inside a SUBDIVISION several same-named cities are small
   *     townships; the most populous is the one an article is about.
   *   - Inside a COUNTRY the same rule would guess — "Springfield, US" —
   *     so it resolves only when the name is unique there or the largest
   *     is dominant (≥ 5× the runner-up: "Paris, FR", "Kyoto, JP").
   *
   * Localized names count, and a Japanese municipality suffix (市/町/村/区)
   * is tolerated because the tables carry "金沢", not "金沢市". Returns
   * None rather than guessing; the caller falls back to `within`.
   */
  def resolveCity(name: String, within: String): Option[Place] = {
    val scope = byCode.get(within).filter(_.kind != PlaceKind.City)
    val key = normalize(name)
    if (scope.isEmpty || key.isEmpty) None
    else {
      def candidatesFor(k: String): Vector[Place] =
        citiesByName.getOrElse(k, Vector.empty).filter(c => ancestors(c.code).exists(_.code == within))
      // The tables are not consistent about the suffix themselves (鎌倉 but
      // 京都市), so try the name as given, then without a suffix, then with
      // each one — whichever the table happens to carry.
      val candidates = {
        val exact = candidatesFor(key)
        if (exact.nonEmpty) exact
        else {
          val stripped = JapaneseMunicipalitySuffixes.iterator
            .filter(s => key.endsWith(s) && key.length > s.length)
            .map(s => candidatesFor(key.dropRight(s.length)))
          val suffixed = JapaneseMunicipalitySuffixes.iterator.map(s => candidatesFor(key + s))
          (stripped ++ suffixed).find(_.nonEmpty).getOrElse(Vector.empty)
        }
      }
      candidates match {
        case Vector()                                              => None
        case Vector(single)                                        => Some(single)
        case many if scope.exists(_.kind == PlaceKind.Subdivision) => many.headOption
        case many                                                  =>
          // Country scope: the largest wins only when it clearly dominates.
          many.headOption.filter(top => top.population >= 5L * many(1).population && top.population > 0L)
      }
    }
  }

  private val JapaneseMunicipalitySuffixes = List("市", "町", "村", "区")

  /**
   * One classifier-emitted place → a code, or None when it cannot be
   * read at all.
   *
   *   - `"JP-17"`          → `Some("JP-17")` (a plain code; `validate` is
   *                          still the gate downstream)
   *   - `"Kanazawa, JP-17"` → `Some("GN1860243")` — the city, resolved in
   *                          scope by [[resolveCity]]
   *   - `"Nowhere, JP-17"`  → `Some("JP-17")` — an unresolvable city
   *                          degrades to the place it was said to be in,
   *                          which is coarser, never wrong
   *   - `"Kanazawa, XX-99"` → `None` — no scope to stand on
   *
   * The split is on the LAST comma so a name containing one still reads.
   */
  def resolveEmitted(raw: String): Option[String] = {
    val s = raw.trim
    val cut = s.lastIndexOf(',')
    if (cut < 0) Option(s).filter(_.nonEmpty)
    else {
      val name = s.substring(0, cut).trim
      val within = s.substring(cut + 1).trim.toUpperCase
      if (!contains(within)) None
      else resolveCity(name, within).map(_.code).orElse(Some(within))
    }
  }

  /** Keep only codes this vocabulary knows. The validation gate. */
  def validate(codes: Iterable[String]): Set[String] = codes.filter(contains).toSet

  def size: Int = byCode.size

  /**
   * Enclosing places, nearest first: `GN1860672` → `[JP-14, JP]`.
   * Excludes the place itself. Cycle-guarded — a malformed table must
   * degrade, not hang.
   */
  def ancestors(code: String): List[Place] = {
    @tailrec
    def loop(current: Option[String], seen: Set[String], acc: List[Place]): List[Place] =
      current.flatMap(byCode.get) match {
        case Some(p) if !seen.contains(p.code) => loop(p.parent, seen + p.code, p :: acc)
        case _                                 => acc.reverse
      }
    byCode.get(code).map(p => loop(p.parent, Set(code), Nil)).getOrElse(Nil)
  }

  /**
   * Expand places to (themselves ∪ their ancestors), keeping the MINIMUM
   * hop distance for each: 0 = named directly, 1 = parent, 2 =
   * grandparent. Mirrors `AuctioneerEntity.expandWithHops` so the two
   * vocabularies decay relevance the same way.
   *
   * Unknown codes contribute nothing — validation is not this method's
   * job, but it must not invent nodes either.
   */
  def expandWithHops(codes: Iterable[String]): Map[String, Int] =
    codes.iterator
      .filter(contains)
      .flatMap(c => (c, 0) +: ancestors(c).zipWithIndex.map { case (p, i) => (p.code, i + 1) })
      .toVector
      .groupMapReduce(_._1)(_._2)(math.min)

  /**
   * Does a campaign's targeting set match a piece of inventory?
   *
   * The inventory side is expanded to ancestors, the targeting side is
   * not. That asymmetry IS the rule: targeting `{JP}` matches a site
   * declaring Kamakura (JP is one of its ancestors), while targeting
   * `{JP-13}` does NOT match inventory that only says `JP` — no
   * descendant match, matching how category targeting already behaves.
   * An advertiser who wants both writes `{JP-13, JP}`.
   *
   * Two boundary cases, both load-bearing:
   *   - empty targeting matches everything (the contextual default,
   *     same as an empty `siteAllowlist`)
   *   - non-empty targeting does NOT match empty inventory. Undeclared
   *     is UNKNOWN, not "everywhere" — see the tier-2 section of
   *     docs/design/GEOGRAPHIC_CONTEXT.md. This falls out of the
   *     expansion rather than needing its own branch, but it is the
   *     rule most likely to be "fixed" by mistake.
   */
  def targetingMatches(targeting: Set[String], inventory: Set[String]): Boolean =
    targeting.isEmpty || expandWithHops(inventory).keysIterator.exists(targeting.contains)

  /**
   * How far a targeting set sits from a piece of inventory, or None when it
   * does not match at all.
   *
   * `Some(0)` means the inventory names a targeted place directly;
   * `Some(1)` its parent; and so on. Untargeted is `Some(0)` — no
   * constraint is a perfect fit, not a distant one, or every untargeted
   * campaign would be quietly penalised.
   *
   * The distinction from [[targetingMatches]] is what the caller does with
   * it: audience targeting is a binary gate, while CONTENT place targeting
   * is relevance, and relevance decays with distance. A campaign targeting
   * Japan on an article about Kamakura is a worse fit than one targeting
   * Kamakura, and should lose to it.
   */
  def matchHops(targeting: Set[String], inventory: Set[String]): Option[Int] =
    if (targeting.isEmpty) Some(0)
    else {
      val expanded = expandWithHops(inventory)
      targeting.iterator.flatMap(expanded.get).minOption
    }

  /** Localized display name for `code` in `lang`, if translated. */
  def nameIn(lang: String, code: String): Option[String] =
    localized.get(LocalizedNames.primary(lang)).flatMap(_.get(code))

  /** Localized name when we have one, else the canonical English name, else the code. */
  def displayName(lang: String, code: String): String =
    nameIn(lang, code).orElse(byCode.get(code).map(_.name)).getOrElse(code)

  /**
   * Type-ahead over English and localized names, for the publisher's
   * audience declaration and the advertiser's targeting picker — both
   * sides pick from the same vocabulary so neither has to type a code.
   *
   * Prefix matches rank above substring matches; within a rank, larger
   * places first (population for cities, and countries/subdivisions
   * ahead of cities since their population is 0 but they are broader).
   */
  def search(query: String, limit: Int = 20): List[Place] = {
    val direct = searchExact(query, limit)
    // Japanese place names are typed with their administrative suffix
    // (石川県, 豊岡市) while the tables carry the bare name (石川, 豊岡) —
    // the same tolerance `resolveCity` extends to the classifier.
    if (direct.nonEmpty) direct
    else
      stripAdminSuffix(query.trim) match {
        case Some(bare) => searchExact(bare, limit)
        case None       => direct
      }
  }

  private val AdminSuffixes = "都道府県市町村区"

  private def stripAdminSuffix(s: String): Option[String] =
    if (s.length > 1 && AdminSuffixes.contains(s.last)) Some(s.dropRight(1)) else None

  private def searchExact(query: String, limit: Int): List[Place] = {
    val q = normalize(query)
    if (q.isEmpty) Nil
    else {
      val kindRank = (p: Place) =>
        p.kind match {
          case PlaceKind.Country     => 0
          case PlaceKind.Subdivision => 1
          case PlaceKind.City        => 2
        }
      searchIndex.iterator
        .collect { case (name, p) if name.startsWith(q) => (0, p) }
        .++(searchIndex.iterator.collect { case (name, p) if !name.startsWith(q) && name.contains(q) => (1, p) })
        .toVector
        .distinctBy { case (rank, p) => (rank, p.code) }
        .sortBy { case (rank, p) => (rank, kindRank(p), -p.population, p.name) }
        .map(_._2)
        .distinctBy(_.code)
        .take(limit)
        .toList
    }
  }

  /** Diacritic- and punctuation-insensitive key, matching the build script. */
  private def normalize(s: String): String = {
    val decomposed = java.text.Normalizer
      .normalize(s, java.text.Normalizer.Form.NFD)
      .toLowerCase
      // NFD splits diacritics into combining marks, which are not
      // letters or digits — so this one filter drops accents and
      // punctuation together. Kana voicing marks are the exception:
      // dropping them makes パリ (Paris) and バリ (Bali) the same word.
      .filter(c => c.isLetterOrDigit || c == '\u3099' || c == '\u309A')
    java.text.Normalizer.normalize(decomposed, java.text.Normalizer.Form.NFC)
  }

  private def loadTsv(resourcePath: String, minCols: Int)(build: Array[String] => Place): Vector[Place] =
    Option(getClass.getResourceAsStream(resourcePath)) match {
      case None =>
        // A missing table is a packaging fault, not a runtime condition —
        // every geographic value would silently fail validation.
        throw new IllegalStateException(s"Place table missing from the classpath: $resourcePath")
      case Some(is) =>
        Using(Source.fromInputStream(is, "UTF-8")) { source =>
          source
            .getLines()
            .drop(1) // header
            .filter(_.nonEmpty)
            .map(_.split("\t", -1))
            .filter(_.length >= minCols)
            .map(build)
            .toVector
        }.get
    }
}
